version: "3.8"

services:
  ml_service:
    build: ./ml_service
    ports:
      - "8000:8000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ml_service

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
