# -*- coding: utf-8 -*-
"""test-inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1el-JiazYxB2R0E5H-6pIN2zutSaTObP8
"""

import time
import torch
import pandas as pd
import os
from transformers import AutoTokenizer, AutoModelForCausalLM
from llama_cpp import Llama
from sentence_transformers import SentenceTransformer, util

BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
FT_MODEL = "./merged_model"
GGUF_MODEL = "./model-q8_0.gguf"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
RESULTS_PATH = "./benchmarks/results.csv"

PROMPTS = [
    "What are the best practices for employee onboarding?",
    "How should performance reviews be conducted?",
    "What are the strategies for improving employee engagement?"
]

GROUND_TRUTH = [
    "Effective employee onboarding includes clear communication of job expectations, introduction to company culture, structured training programs, mentorship, and regular check-ins to ensure smooth integration.",
    "Performance reviews should be conducted regularly, combining self-assessment, manager feedback, goal tracking, and constructive discussion to guide career development and improve performance.",
    "Employee engagement can be improved by recognizing achievements, providing growth opportunities, maintaining open communication, promoting work-life balance, and fostering a positive work environment."
]

embedder = SentenceTransformer("BAAI/bge-base-en-v1.5")

def get_vram():
    if torch.cuda.is_available():
        return torch.cuda.memory_allocated() / 1024**2
    return 0

def accuracy(preds, refs):
    p_emb = embedder.encode(preds, convert_to_tensor=True)
    r_emb = embedder.encode(refs, convert_to_tensor=True)
    sims = util.cos_sim(p_emb, r_emb)
    return sims.diag().mean().item()

def benchmark_hf(model_path, label):
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForCausalLM.from_pretrained(model_path, device_map=DEVICE)
    outputs = []
    start = time.time()
    for prompt in PROMPTS:
        input_ids = tokenizer(prompt, return_tensors="pt").to(DEVICE)
        out = model.generate(**input_ids, max_new_tokens=128)
        outputs.append(tokenizer.decode(out[0], skip_special_tokens=True))
    end = time.time()
    tokens = sum(len(tokenizer.encode(r)) for r in outputs)
    tps = tokens / (end - start)
    acc = accuracy(outputs, GROUND_TRUTH)
    return {"Model": label, "Tokens/sec": round(tps,2), "Latency(s)": round(end-start,2), "VRAM(MB)": round(get_vram(),2), "Accuracy": round(acc,3)}

def benchmark_gguf(label):
    llm = Llama(model_path=GGUF_MODEL, n_ctx=2048, n_threads=8, verbose=False)
    outputs = []
    start = time.time()
    for prompt in PROMPTS:
        out = llm(prompt, max_tokens=128)
        outputs.append(out["choices"][0]["text"])
    end = time.time()
    tokens = sum(len(o.split()) for o in outputs)
    tps = tokens / (end - start)
    acc = accuracy(outputs, GROUND_TRUTH)
    return {"Model": label, "Tokens/sec": round(tps,2), "Latency(s)": round(end-start,2), "VRAM(MB)": round(get_vram(),2), "Accuracy": round(acc,3)}

if __name__ == "__main__":
    os.makedirs("benchmarks", exist_ok=True)
    results = []

    for i in range(3):
        results.append(benchmark_gguf("GGUF Q8 llama.cpp"))
        results.append(benchmark_hf(BASE_MODEL, "Base Model"))
        results.append(benchmark_hf(FT_MODEL, "Fine-tuned"))

    df = pd.DataFrame(results)
    df.to_csv(RESULTS_PATH, mode='a', index=False)
    print(df)

